version: '3'
services:
  web:

  postgres:
    build: ./docker/postgres
    ports:
    - "5473:5473"
    - "5432:5432"
  kafka:
    image: "landoop/fast-data-dev:latest"
    environment:
    - ADV_HOST=127.0.0.1
    ports:
    - "2181:2181"
    - "3030:3030"
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "9092:9092"
